-- Get all tables in VIA database
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' 
AND TABLE_NAME LIKE '%Schedule%' OR TABLE_NAME LIKE '%Time%' OR TABLE_NAME LIKE '%Access%' OR TABLE_NAME LIKE '%Reader%'
ORDER BY TABLE_NAME;

-- Get columns for HW_Devices to see if there are priority/mask fields
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'HW_Devices'
ORDER BY ORDINAL_POSITION;

-- Get columns for HW_Controllers
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'HW_Controllers'
ORDER BY ORDINAL_POSITION;
